### ISSUE TITLE
I remove my previous cluster

### ISSUE THREAD

**Issue by ericsonluciano** [graphcool/prisma-cloud-feedback#63]
after i delete my cluster page and try to connect new cluster it's become blank but the chat of intercom still on active on console here the error

`react-dom.production.min.js:164 TypeError: Cannot read property 'workspace' of undefined
    at Clusters.tsx:75
    at t.render (react-apollo.browser.umd.js:1)
    at u (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at o (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:161)
    at s (react-dom.production.min.js:162)
    at w (react-dom.production.min.js:169)
    at _ (react-dom.production.min.js:168)
    at h (react-dom.production.min.js:167)`

`Unhandled error GraphQL error: GraphQL Error (Code: 503)
GraphQL error: GraphQL Error (Code: 503) Error: GraphQL error: GraphQL Error (Code: 503)
GraphQL error: GraphQL Error (Code: 503)
    at new t (https://app.prisma.sh/static/js/main.b5b5c41b.js:1:410489)
    at https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1266513
    at https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1273340
    at Array.forEach (<anonymous>)
    at https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1273320
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1273227)
    at Object.next (https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1274005)
    at p.next (https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1251680)
    at https://app.prisma.sh/static/js/main.b5b5c41b.js:1:1276979`

`Clusters.tsx:75 Uncaught TypeError: Cannot read property 'workspace' of undefined
    at Clusters.tsx:75
    at t.render (react-apollo.browser.umd.js:1)
    at u (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at o (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:161)
    at s (react-dom.production.min.js:162)
    at w (react-dom.production.min.js:169)
    at _ (react-dom.production.min.js:168)
    at h (react-dom.production.min.js:167)`

**Comment by timsuchanek** [comment]
Thanks for reporting @ericsonluciano !
Your account is cleaned up and should be in a good state again.
